name: VeloxClaim
main: veloxclaimprotection.VeloxClaimProtection
version: 1.0.0-prerelease-1
api-version: 1.21
softdepend: [Vault]
commands:
  lands:
    description: 'The main UltrasClaim command'
    usage: '/<command> [subcommand]'
    aliases:
     - land
    permission: veloxclaim.lands
permissions:
  veloxclaim.lands:
    description: "Allow a player to run the command: /lands"
    default: true